# Supported URL formats from the libSQL JDBC driver include:
# libsql://your-database.turso.io
# jdbc:dbeaver:libsql:https://your-database.turso.io
#spring.datasource.url=${TURSO_DATABASE_URL}

spring.datasource.url=libsql://appointley-jasnrathore.aws-ap-south-1.turso.io
spring.datasource.driver-class-name=com.dbeaver.jdbc.driver.libsql.LibSqlDriver
spring.datasource.username=
spring.datasource.password=${TURSO_AUTH_TOKEN}
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.batch_size=1
spring.jpa.properties.hibernate.order_inserts=false
spring.jpa.properties.hibernate.order_updates=false
spring.jpa.show-sql=true
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.auto-commit=true
spring.datasource.hikari.connection-test-query=SELECT 1
server.port=8080
