spring.application.name=appointley
spring.profiles.default=postgres
app.jwt.secret=${JWT_SECRET:appointley-super-secret-key-appointley-super-secret-key-2026}
app.jwt.access-token-minutes=15
app.jwt.refresh-token-days=14
app.frontend.base-url={BACKEND_DOMAIN}
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# Mail Settings
spring.mail.host=smtp.gmail.com
spring.mail.port=587
#spring.mail.username=${MAIL_USERNAME:your-email@gmail.com}
#spring.mail.password=${MAIL_PASSWORD:your-app-password}

spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
