package com.jpr.clss.entity;

public enum EmailType {
    TEAM_INVITE,
    MEETING_BOOKED_ORGANIZER,
    MEETING_BOOKED_CLIENT,
    MEETING_CANCELLED_ORGANIZER,
    MEETING_CANCELLED_CLIENT,
    MEETING_RESCHEDULED_ORGANIZER,
    MEETING_RESCHEDULED_CLIENT,
    REMINDER,
    BOOKING_LINK,
    PASSWORD_RESET,
    ROLE_UPDATED
}
